### ISSUE TITLE
Creative way of allowing option<string> as a parameter

### ISSUE THREAD

**Issue by kanishka-work** [shakacode/rescript-classnames#13]
Is there some creative way of using ReScript syntax to allow each argument to be either a string or an option<string>? It would be nice to have such a convenience.

**Comment by sudo97** [comment]
You could have your own type with all possible variants you want.

`type t = Cnst(string) | Optional(option<string>) | Boolean(string, bool)`

But this way you would wrap all of your values, and pattern-match them later

**Comment by alexfedoseev** [comment]
I don't think it's possible w/o ppx, which is not gonna make it into this library for the reasons I elaborated on [here](https://github.com/shakacode/rescript-classnames/issues/14#issuecomment-853727163).
