### ISSUE TITLE
Implementation discussion

### ISSUE THREAD

**Issue by sudo97** [shakacode/rescript-classnames#14]
Hi, I'm really interested in the rescript and what it can grow into. I liked your idea of classnames reimplementaion. But what I've seen so far can be just done in one line:
`let make = (names: array<string>) => names->Js.Array2.joinWith(" ")`

I was just wondering if you're interested in making it more flexible with a few possible ways to concat a classname.

**Comment by alexfedoseev** [comment]
Hi,

This library went through many API iterations and the current API is what the community decided to be an optimal compromise between usability and performance. You can check out [this discussion](https://forum.rescript-lang.org/t/a-bit-of-perspective-on-infix-operators-and-readability-p/501/14?u=alex.fedoseev) for more details.

P.S.
> But what I've seen so far can be just done in one line: let make = (names: array<string>) => names->Js.Array2.joinWith(" ")

In this case, you'd get multiple spaces in the output. If you don't care about it, using string interpolation would give you much better performance.

**Comment by sudo97** [comment]
Thanks for the quick reply. I only discovered Rescript about a month ago, so I don't even know where to look yet.

**Comment by alexfedoseev** [comment]
NP!
